version: "3.5"

services:

  nginx:
    image: arkanion/custom-nginx:1.0
    restart: unless-stopped
    volumes:
      - ./index.html:/data/www/index.html
    ports:
      - 8080:8080
    environment:
      - NGINX_PORT=8080
