- name: install dependencies
  hosts: my-hosts
  become: true
  tasks:
    - name: update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: "Add Docker gpg key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Add docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: "Install Docker"
      apt:
        pkg:
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"
        state: present
        update_cache: true

    - name: Install docker-compose
      command: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

    - name: chmod docker-compose
      command: chmod +x /usr/local/bin/docker-compose

- name: runing app
  hosts: my-hosts
  tasks:
    - name: git clone