- name: install dependencies
  hosts: my-hosts
  become: true
  tasks:
    - name: update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: "Add Docker gpg key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Add docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        filename: docker

    - name: "Install Docker"
      apt:
        pkg:
          - "docker-ce"
          - "docker-ce-cli"
          - "containerd.io"
`          - docker-compose-plugin
        state: present
        update_cache: true

- name: preraring app
  hosts: my-hosts
  vars:
    YOUR_NAME: Arkanion
  tasks:
    - name: git clone
      command: git clone https://github.com/arkani0n/docker-terraform-ansilble

    - name: update index.html
      command: echo "Hello from ${{ YOUR_NAME }}" > ~/docker-terraform-ansilble/docker/index.html

- name: run app
  hosts: my-hosts
  become: true
  tasks:
    - name: docker run
      command: cd ~/docker-terraform-ansilble/docker/ && docker compose up -d
